/**
 * Created by bradjones on 11/5/16.
 */
    require([
        "dojo/dom-construct",
        "esri/Map",
        "esri/views/MapView",
        // "esri/layers/FeatureLayer",
        "esri/layers/MapImageLayer",
        "esri/layers/support/LabelClass",
        "esri/symbols/TextSymbol",
        "esri/symbols/SimpleMarkerSymbol",
        "esri/renderers/SimpleRenderer",
        "esri/renderers/UniqueValueRenderer",
        "esri/PopupTemplate",
        "esri/widgets/Legend",
        "dojo/dom",
        "dojo/on",
        "dojo/domReady!"
    ],
        function(
            domConstruct,
            Map,
            MapView,
            // FeatureLayer,
            MapImageLayer,
            LabelClass,
            TextSymbol,
            SimpleMarkerSymbol,
            SimpleRenderer,
            UniqueValueRenderer,
            PopupTemplate,
            Legend,
            dom,
            on
    ) {



        // Popup template for wards
        // ****Stats files in popup are generated by a scheduled task on server SQL1****
        var wardsPopupTemplate = new PopupTemplate({
            title: "Ward {DISTRICT} - {NAME}",
            content: "<iframe src='{WEBSITE}' frameborder='0' width='100%' " +
        "height='100%' "+"style='width: 100%; height: 100%; display: block; padding: 0px; margin: 0px;'></iframe>"
        });

        /*****************************************************************
        * Create renderers for each SSLRP Layer
        *****************************************************************/
         // Symbol variables for the UniqueValueRenderer based on sslrpTotal
        var sslrpSymb1 = SimpleMarkerSymbol({
            style: "circle",
            size: "7",
            color: "purple",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymb2 = SimpleMarkerSymbol({
            style: "circle",
            size: "7",
            color: "blue",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymb3 = SimpleMarkerSymbol({
            style: "circle",
            size: "6",
            color: "red",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymb4 = SimpleMarkerSymbol({
            style: "circle",
            size: "7",
            color: "green",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymb5 = SimpleMarkerSymbol({
            style: "circle",
            size: "7",
            color: "black",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymb6 = SimpleMarkerSymbol({
            style: "circle",
            size: "6",
            color: "orange",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymb7= SimpleMarkerSymbol({
            style: "circle",
            size: "6",
            color: "yellow",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymb0 = SimpleMarkerSymbol({
            style: "circle",
            size: "6",
            color: "33FF3C",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        // Symbol variables for the UniqueValueRenderer based on sslrpYear
        var sslrpSymbYear1 = SimpleMarkerSymbol({
            style: "square",
            size: "7",
            color: "purple",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymbYear2 = SimpleMarkerSymbol({
            style: "square",
            size: "7",
            color: "blue",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymbYear3 = SimpleMarkerSymbol({
            style: "square",
            size: "6",
            color: "red",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymbYear4 = SimpleMarkerSymbol({
            style: "square",
            size: "7",
            color: "green",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymbYear5 = SimpleMarkerSymbol({
            style: "square",
            size: "7",
            color: "black",
            outline: {
            width: 0.5,
            color: "white"
            }
        });

        var sslrpSymbYear6 = SimpleMarkerSymbol({
            style: "square",
            size: "6",
            color: "orange",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymbYear7= SimpleMarkerSymbol({
            style: "square",
            size: "6",
            color: "yellow",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        var sslrpSymbyear0 = SimpleMarkerSymbol({
            style: "square",
            size: "6",
            color: "33FF3C",
            outline: {
            width: 0.5,
            color: "black"
            }
        });

        // UniqueValueRenderer based on sslrp wards for total reimbursed.
        var sslrpTotalRenderer = new UniqueValueRenderer({
            field: "DISTRICT",
            uniqueValueInfos: [
                {
                value: "1",
                symbol: sslrpSymb1,
                label: "Ward 1- Hendrix"
                },{
                value: "2",
                symbol: sslrpSymb2,
                label: "Ward 2- Richardson"
                }, {
                value: "3",
                symbol: sslrpSymb3,
                label: "Ward 3- Webb"
                }, {
                value: "4",
                symbol: sslrpSymb4,
                label: "Ward 4- Peck"
                }, {
                value: "5",
                symbol: sslrpSymb5,
                label: "Ward 5- Hines"
                }, {
                value: "6",
                symbol: sslrpSymb6,
                label: "Ward 6- Wright"
                }, {
                value: "7",
                symbol: sslrpSymb7,
                label: "Ward 7- Wyrick"
                }, {
                value: "0",
                symbol: sslrpSymb0,
                label: "Outside City"
                }]
        });

        // UniqueValueRenderer based on sslrp wards for current calendar year.
        var sslrpYearRenderer = new UniqueValueRenderer({
            field: "DISTRICT",
            uniqueValueInfos: [
                {
                value: "1",
                symbol: sslrpSymbYear1,
                label: "Ward 1- Hendrix"
                },{
                value: "2",
                symbol: sslrpSymbYear2,
                label: "Ward 2- Richardson"
                }, {
                value: "3",
                symbol: sslrpSymbYear3,
                label: "Ward 3- Webb"
                }, {
                value: "4",
                symbol: sslrpSymbYear4,
                label: "Ward 4- Peck"
                }, {
                value: "5",
                symbol: sslrpSymbYear5,
                label: "Ward 5- Hines"
                }, {
                value: "6",
                symbol: sslrpSymbYear6,
                label: "Ward 6- Wright"
                }, {
                value: "7",
                symbol: sslrpSymbYear7,
                label: "Ward 7- Wyrick"
                }, {
                value: "0",
                symbol: sslrpSymbyear0,
                label: "Outside City"
                }]
        });


        /*****************************************************************
        * Create a MapImageLayer instance with three sublayers pointing
        * to a single map service layer. Each layer uses the same data
        * but dynamically renders the data differently for each layer.
        *****************************************************************/

        var wardsLayers = new MapImageLayer({
                url: "https://gis.lrwu.com/arcgis/rest/services/SSLRP/MapServer",
                title: "Wards",
                sublayers: [{
                    id: 0,
                    title: "Ward 1- Hendrix",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 1
                    }
                },{
                    id: 1,
                    title: "Ward 2- Richardson",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 2
                    }
                }, {
                    id: 2,
                    title: "Ward 3- Webb",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 3
                    }
                }, {
                    id: 3,
                    title: "Ward 4- Peck",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 4
                    }
                }, {
                    id: 4,
                    title: "Ward 5- Hines",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 5
                    }
                }, {
                    id: 5,
                    title: "Ward 6- Wright",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 6
                    }
                }, {
                    id: 6,
                    title: "Ward 7- Wyrick",
                    visible: true,
                    popupTemplate: wardsPopupTemplate,
                    source: {
                        mapLayerId: 7
                    }
                }]
        });



        var sslrpLayers = new MapImageLayer({
            url: "https://gis.lrwu.com/arcgis/rest/services/SSLRP/MapServer",
            title: "Applications",
            sublayers: [{
                id: 0,
                title: "Reimbursed Since 1/1/2013",
                visible: true,
                renderer: sslrpTotalRenderer,
                definitionExpression: "STATUS = 'Reimbursed'",
                source: {
                    mapLayerId: 0
                }
            },{
                id: 1,
                title: "Reimbursed Current Calendar Year",
                visible: false,
                definitionExpression: "PROBDTTM > '12/29/2017 4:18:34 PM' AND STATUS = 'Reimbursed'",
                renderer: sslrpYearRenderer,
                source: {
                    mapLayerId: 0
                }
            }]
        });


        /*****************************************************************
        * Add the layer to a map
        *****************************************************************/
        var logo = domConstruct.create("img", {
            src: "https://gis.lrwu.com/sslrp/images/sslrp_logo.png",
            id: "logo",
            title: "logo"
        });

        var map = new Map({
        basemap: "gray",
        layers: [wardsLayers, sslrpLayers]
        });


        var view = new MapView({
        container: "viewDiv",
        map: map,
        zoom: 13,
        center: [-92.356121,34.737015],
        logo: false
        });

        var legend = new Legend({
            view: view,
            layerInfos: [{
                layer: sslrpLayers
            }]
        });


        // view.ui.move("zoom", "top-left");
        view.ui.add(legend, "bottom-left");
        view.ui.add("select-div", "top-right");

      // set sublayer visibility depending on the selected layer
      on(dom.byId("layer-select"), "change", function(event) {
        var newValue = parseInt(event.target.value);
        sslrpLayers.sublayers.forEach(function(sublayer) {
          sublayer.visible = (newValue === sublayer.id);
        });
      });

    });